### ISSUE TITLE
局部引入方式，css在main.js下引用无法加载

### ISSUE THREAD

**Issue by 378406712** [lpreterite/vue-tinymce-example#101]
![image](https://user-images.githubusercontent.com/49616257/221770681-6ba8ce97-0a15-4bb8-9b60-94e35968d622.png)
![image](https://user-images.githubusercontent.com/49616257/221770739-96c6970d-04a4-4d7c-b328-aa63d646343b.png)

**Comment by lpreterite** [comment]
其实没必要引入，目前例子已移除这个引入项。 见: https://github.com/lpreterite/vue-tinymce-example/blob/master/vue-cli/use_import/src/main.js#L7
