### ISSUE TITLE
vue项目中通过按需引入的方式不生效

### ISSUE THREAD

**Issue by G-WangZH** [lpreterite/vue-tinymce-example#58]
在vue项目中，通过按需引入的方式，发现content.min.css没有成功引入进来，按照文档引入的，不知道怎么回事
![image](https://user-images.githubusercontent.com/24827526/137064279-b4557b5e-5079-42ce-a849-74694beac06b.png)

**Comment by lpreterite** [comment]
因tinymce版本不同文件目录有变化，请去node_modules/tinymce目录中找到相应的文件，再将其引入。

**Comment by 378406712** [comment]
是从对应版本node_modules/tinymce路径下找的，还是无法引入

**Comment by lpreterite** [comment]
目前知道的是，import方式引用编辑器中文本样式是无效的，具体见 #101
